### ISSUE TITLE
Support locale-specific pluralization rules

### ISSUE THREAD

**Issue by mamantoha** [crimson-knight/i18n.cr#17]
Provide a pluralization backend that can be used to enable locale-specific rules.

Right not there are only two forms, a singular and a plural, for a given string, e.g. "1 message" and "2 messages". Some other languages have different grammars that have additional or fewer plural forms.

**Comment by imdrasil** [comment]
As far as I can see this is no longer an issue. If you still have some issue related to this topic feel free to reopen
