### ISSUE TITLE
Get iterator size

### ISSUE THREAD

**Issue by watzon** [crimson-knight/i18n.cr#21]
Is there a way to get the number of items in a list? I want to provide multiple items to the list and randomly pick one, but to do so I'd need to know for sure how many items that list contains.

**Comment by TechMagister** [comment]
There is no way to do this for the moment :/

**Comment by imdrasil** [comment]
With the current implementation this can be achieved by accessing root key of array:

```yaml
message:
  - a
  - b
```

```crystal
I18n.translate("message") # ["a", "b"]
```

After this you can get array element
