### ISSUE TITLE
Configuration should be on a per-instance basis

### ISSUE THREAD

**Issue by watzon** [crimson-knight/i18n.cr#24]
So I had a really weird bug in a project I'm working on that I've been trying to solve for the past 2 hours. I was trying to get the list of available locales from the backend using `I18n.available_locales`, but it was returning "en" twice, as well as a locale that wasn't in my project at all.

After a lot of digging I found out that another project that I'm using, humanize_time, also uses I18n and that the mysterious locale was coming from there.

Ideally configuration should be done on a project by project basis, not globally.

**Comment by imdrasil** [comment]
I may get your point wrongly but from my perspective application should have a single instance with translations that is shared with all libraries and application itself. Doing this you can customize translation for some libraries and also use some translations from underling libraries in project code. What do you think about this? Also do you still have any issue connected to this topic?

**Comment by crimson-knight** [comment]
@watzon what framework are you using and finding this issue with?

**Comment by watzon** [comment]
This was quite a while ago, but iirc I was trying to integrate `i18n` with my library tourmaline to create a bot. I was also using `humanize_time` which uses `i18n` as well and that's where this bug popped up.

I agree with @imdrasil that ideally, libraries shouldn't use `i18n` directly, but in the event that they don't it would still be nice not to encounter this issue.

**Comment by imdrasil** [comment]
@watzon technically any lib/application can instantiate dedicated backend instance to have own translations that aren't shared with other context

```crystal
MY_I18N = I18n::Backend::Yaml.new
MY_I18N.load("my/location")
# ...
MY_I18N.translate("en", "hello")
```

It is a bit limited compared to global `I18n.translate` but I still think that it should be ok to use global context

**Comment by crimson-knight** [comment]
I'm going to close this issue since it doesn't appear to be holding anyone back at this point.
