### ISSUE TITLE
I18n fallbacks support?

### ISSUE THREAD

**Issue by vifreefly** [crimson-knight/i18n.cr#8]
Is there locales fallbacks feature? For example in Rails I can setup fallbacks this way:

```
# config/application.rb

config.i18n.fallbacks = { :'en-US' => :en, :'en-GB' => :en, :'en-AU' => :en, :'ru-RU' => :ru, ru: :en }
``` 
Like you see I have 3 English based locales - `en-US`, `en-GB` and `en-AU`. Most of content is common between them, so this is good idea to fallback to the `en` localization file, if there is no specific key in `en-*` locales.  

> Here is additional info about fallbacks: https://stackoverflow.com/a/26324977/10678502

**Comment by TechMagister** [comment]
Hello,

There are no fallback for the moment. Waiting for someone contribution ?

**Comment by vifreefly** [comment]
@TechMagister  I have plans to migrate my Rails app to the Amber app. If it will happen, then there will be a PR with this feature :)

**Comment by crimson-knight** [comment]
@vifreefly the fallbacks feature has been added into the master branch and I'll launch it as a new release version soon
